#!/bin/bash
# This script created by AQEMU
dir=/var/lib/vmalpine
args=(-soundhw ac97 \
	-machine accel=kvm \
	-m 1024 \
	-hda "${dir}/alpine.qcow2" \
	-net nic,macaddr=52:54:00:f4:78:8a,model=virtio \
	-net tap,ifname=tap0,script=/usr/local/sbin/qemu-ifup \
	-rtc base=localtime \
	-pflash "/var/lib/vmalpine/OVMF.fd" \
	-name "alpine")
/usr/bin/qemu-system-x86_64 "${args[@]}"
