#!/bin/bash
rm -d /media/e/bbR7qvRSTN4BmaJ
mkdir -p /media/e/bbR7qvRSTN4BmaJ
chown e:e /media/e/bbR7qvRSTN4BmaJ
cryptsetup luksOpen -d /root/luksKey /dev/disk/by-uuid/36dea421-101d-45b1-a22b-9816f3c43205 luks-36dea421-101d-45b1-a22b-9816f3c43205
mount -o ro /dev/mapper/luks-36dea421-101d-45b1-a22b-9816f3c43205 /media/e/bbR7qvRSTN4BmaJ
#mount -o remount,ro /dev/mapper/luks-36dea421-101d-45b1-a22b-9816f3c43205

