#!/bin/bash
pid="$1"
pid="${pid:-twitter}"
#shift
shift
cmder="$@"

netdev="enx001e101f0000"
#netfilter="/etc/firejail/nolocal.net"
netfilter="/home/e/.firejail/nolocal.net"
netfilter6="/home/e/.firejail/nolocal6.net"
#enx001e101f0000

#privatehome='.mozilla,.config,.tor,torrc'


#if firejail --net.print="$pid"; then 
#filter="--net=${net} --netfilter=/etc/firejail/nolocal.net --netfilter6=/etc/firejail/nolocal6.net"
#--netfilter6="$netfilter6"
#echo $netfilter
#exit;
#fi

if ! firejail --ls="$pid" ~; then
#	firejail --name="$pid" --profile=firefox --x11=xephyr --net="${netdev}" --netfilter=1olocal --netfilter6=/etc/firejail/nolocal6.net  --dns=192.168.8.1 --private="~/twitter" --noroot --caps.drop=all --disable-mnt  --private-tmp  --nodbus --private-dev --machine-id  --noautopulse --nou2f --nodvd  --notv --novideo  --ipc-namespace -- openbox &
args=(--name="$pid" \ 
	--protocol=unix,inet \
	--profile=firefox \
	--x11=xephyr \
	--net="${netdev}" \
	--netfilter="$netfilter" \
	--defaultgw=192.168.8.1 \
	--dns=192.168.8.1 \
	--private="~/firejail/${pid}" \
	--nonewprivs \
	--nogroups \
	--noroot \
	--caps.drop=all \
	--disable-mnt  \
	--private-tmp  \
	--nodbus \
	--private-dev \
	--machine-id  \
	--noautopulse \
	--nou2f \
	--nodvd \
	--no3d \
	--notv \
	--novideo \
	--nosound \
	--ipc-namespace \
	openbox)
	
#firejail "${args[@]}" < /dev/null
firejail --name="$pid" --protocol=unix,inet --profile=firefox --x11=xephyr --net="${netdev}" --netfilter="$netfilter" --dns=192.168.8.1 --private="~/firejail/${pid}" --nonewprivs --nogroups --noroot --caps.drop=all --disable-mnt --private-tmp --nodbus --private-dev --machine-id --noautopulse --nou2f --nodvd --no3d --notv --novideo --nosound --ipc-namespace 	openbox &
sleep 3s
#	firejail --bandwidth="$pid" set "$netdev" 24 8
#else
#	sleep 3s
fi
echo firejail --join="$pid" "$@"
firejail --join="$pid" "$@"
#firejail --join="$pid" firefox -P "$@" &
#firejail --join="$pid" firefox "$@" &

