#!/bin/bash
q="$*"
mkdir -p "$HOME/Documents/" 2> /dev/null
mkdir -p "$HOME/Documents/cht.sh" 2> /dev/null

qcachefile="$HOME/Documents/cht.sh/$q"

if [[ ! -f "$qcachefile" ]]; then
	netbox sh -c "curl https://cht.sh/$q ^| tee -a $qcachefile"
else 


	echo === cached: $q ===== 
	echo .
	cat "$qcachefile"
fi




