#!/bin/bash
q="$1"
mkdir -p "$HOME/Documents/" 2> /dev/null
mkdir -p "$HOME/Documents/cht.sh" 2> /dev/null

qcachefile="$HOME/Documents/cht.sh/$q"

if [[ ! -f "$qcachefile" ]]; then
	netbox curl "https://cht.sh/$q" -o "$qcachefile"
fi

	echo === cached: $q ===== 
	echo .
	cat "$qcachefile"
