#!/bin/bash
targetdir="$HOME/.sha1sum"; 
mkdir -p "$targetdir"; 

while read f; do 
    if [[ -f $f ]] && [[ ! -L $f ]]; then 
      sum=$(sha1sum -b < "$f" | awk '{ print $1 }');     
      target="$targetdir/$sum"; 
      mv -v "$f" "$target"; 
      ln -s "$target" "$f"; 
    fi
done
