#!/bin/bash
pendev=/dev/sdb1
mountdir=/media/e/bbR7qvRSTN4BmaJ

if [[ ! -f $pendev ]]; then
#pendev=/dev/sdc1
echo $pendev
fi
sleep 2s
sudo mkdir -p "$mountdir"
sudo chown -R e:e "$mountdir"
sudo cryptsetup luksOpen -d /root/luksKey "$pendev" dong
sudo mount -o ro /dev/mapper/dong "$mountdir"
sudo mount -o bind "$mountdir" "$mountdir"1
