#!/bin/bash
pendev=/dev/sdb1
if [[ ! -f $pendev ]]; then
#pendev=/dev/sdc1
echo $pendev
fi
sleep 2s
sudo mkdir -p /media/e/bbR7qvRSTN4BmaJ
sudo chown -R e:e /media/e/bbR7qvRSTN4BmaJ
sudo cryptsetup luksOpen -d /root/luksKey $pendev dong
sudo mount -o ro /dev/mapper/dong /media/e/bbR7qvRSTN4BmaJ
