#!/bin/bash
rl(){
	local count=0
	cat "$1" - | while read line; do 
		if [[ "x" = x$line ]] && ((count>1)); then 
			exit 0
		elif [[ -z $line ]]; then
			((count++))
		else 
			((count=0))
		fi
		printf %s\\n "$line" 
	done
}


if which "$1"; then 
	fullpath=$(which "$1");
	nano "$fullpath"
else
	fullpath="$HOME/.local/bin/$1"

	if [[ ! -f $fullpath ]]; then
		touch "$fullpath"
		chmod +x "$fullpath"
		echo '#!/bin/bash' >  "$fullpath"
		cat "$fullpath" - > "$fullpath"
	fi
fi
#cp -f "$fullpath" "${fullpath%/*}/bin/${fullpath##*/}"
#cat "$fullpath" - > "$fullpath"