#!/bin/bash
home=$HOME/firejail/openbox
cd "$home"
id=$(hhash)
[[ ! -d $HOME/Pictures/.txt ]] && mkdir -p $HOME/Picures/.txt
cat **/images*.txt | sort | tee "$HOME/Pictures/.txt/$id.txt"
rm **/images*.txt
exit 0;
[[ ! -d $HOME/Pictures/new ]];  mkdir -p $HOME/Pictures/new
[[ ! -d $HOME/Pictures/new/$id ]];  mkdir -p $HOME/Pictures/new/$id
cd $HOME/Pictures/new/id
netbox wwget -i $HOME/Pictures/.txt/$id.txt

