#!/bin/bash
# clean up firejail working/private-home directory
#firejaildir="$1"
firejaildir="/home/e/firejail/openbox"

#if [[ ! -d $firejaildir ]]; then
#  notify 'Missing Argument Error: f-restore <firejaildir>'
#  exit 1
#fi

verbose=""
profilename="${1:-profile.twitter}"
profile="${firejaildir}/.mozilla/firefox/${profilename}"
profilebackup="/opt/backup/.mozilla/firefox/${profilename}"
cache="${firejaildir}/.cache"
cachebackup="/opt/backup/.cache/mozilla"

##rm -rf "$firejaildir/.tor"
#cp -a "$verbose" "$HOME/.tor" "$firejaildir"
#rm $firejaildir/.Xauthority
#rm -rf "${firejaildir}/.local"
#rm -rf "${firejaildir}/.config"
#rm -rf "${firejaildir}/.mozilla/firefox/Crash*"


#rm -rf "${profile}.bak"
#cp -a "$verbose" "$profile" "${profile}.bak"


#cp -f "$profile/places.sqlite" "$profilebackup/"

if [[ -d "$profilebackup" ]]; then
    echo cp -a "$verbose" "$profilebackup" "${profile%/*}"
    rm -rf "$profile"    
    cp -a "$verbose" "$profilebackup" "${profile%/*}"
    rm -rf "$firejaildir/.cache"
    mkdir -p "$firejaildir/.cache"
    cp -a "$verbose" "$cachebackup" "$cache"
fi

