#!/bin/bash
# clean up firejail working/private-home directory
firejaildir="$HOME/firejail/twitter"
verbose="-v"
profile="${firejaildir}/.mozilla/firefox/1rymm6oy.twitter"
profilebackup="$HOME/Downloads/backup/.mozilla/firefox/profile.twitter"
cache="${firejaildir}/.cache/mozilla"
cachebackup="$HOME/Downloads/backup/.cache/mozilla"

##rm -rf "$firejaildir/.tor"
#cp -a "$verbose" "$HOME/.tor" "$firejaildir"
#rm $firejaildir/.Xauthority
#rm -rf "${firejaildir}/.local"
#rm -rf "${firejaildir}/.config"
#rm -rf "${firejaildir}/.mozilla/firefox/Crash*"


rm -rf "${profile}.bak"
cp -a "$verbose" "$profile" "${profile}.bak"

rm -rf "$profile"
cp -a "$verbose" "$profilebackup" "$profile"

rm -rf "$cache"
cp -a "$verbose" "$cachebackup" "$cache"