#!/bin/bash
# clean up firejail working/private-home directory
firejaildir="$1"

if [[ ! -d $firejaildir ]]; then
  notify 'Missing Argument Error: f-restore <firejaildir>'
  exit 1
fi

verbose="-v"
profile="${firejaildir}/.mozilla/firefox/1rymm6oy.twitter"
profilebackup="$HOME/Downloads/backup/.mozilla/firefox/profile.twitter"
cache="${firejaildir}/.cache/mozilla"
cachebackup="$HOME/Downloads/backup/.cache/mozilla"

##rm -rf "$firejaildir/.tor"
#cp -a "$verbose" "$HOME/.tor" "$firejaildir"
#rm $firejaildir/.Xauthority
#rm -rf "${firejaildir}/.local"
#rm -rf "${firejaildir}/.config"
#rm -rf "${firejaildir}/.mozilla/firefox/Crash*"


rm -rf "${profile}.bak"
#cp -a "$verbose" "$profile" "${profile}.bak"


cp -f "$profile/places.sqlite" "$profilebackup/places.sqlite"

rm -rf "$profile"
cp -a "$verbose" "$profilebackup" "$profile"

rm -rf "$firejaildir/.cache"
mkdir -p "$firejaildir/.cache"
cp -a "$verbose" "$cachebackup" "$cache"