#!/bin/bash
# clean up firejail working/private-home directory
firejaildir="$HOME/firejail/twitter"

profile="${firejaildir}/.mozilla/firefox/1rymm6oy.twitter"
profilebackup="$HOME/Downloads/backup/.mozilla/firefox/profile.twitter"
cache="${firejaildir}/.cache/mozilla"
cachebackup="$HOME/Downloads/backup/.cache/mozilla"

rm -rf "${profilebackup}.bak"
cp -a "$verbose" "$profilebackup" "${profilebackup}.bak"
rm -rf "$profilebackup"
cp -a "$verbose" "$profile" "$profilebackup"
rm -rf "$profile"

rm -rf "$cachebackup.bak"
cp -a "$verbose" "$cachebackup" "$cachebackup.bak"
rm -rf "$cachebackup"
cp -a "$verbose" "$cache" "$cachebackup"