#!/bin/bash
# clean up firejail working/private-home directory
firejaildir="$HOME/firejail/openbox"

profilename="${1:-profile.twitter}"
profile="${firejaildir}/.mozilla/firefox/$profilename"
profilebackup="/media/e/backup/.mozilla/firefox/$profilename"
cache="${firejaildir}/.cache/mozilla"
cachebackup="/media/e/backup/.cache/mozilla"

rm -rf "${profilebackup}.bak"
cp -a "$verbose" "$profilebackup" "${profilebackup}.bak"
rm -rf "$profilebackup"
cp -a "$verbose" "$profile" "$profilebackup"
rm -rf "$profile"

rm -rf "$cachebackup.bak"
cp -a "$verbose" "$cachebackup" "$cachebackup.bak"
rm -rf "$cachebackup"
cp -a "$verbose" "$cache" "$cachebackup"
