#!/bin/bash
file="$1"

if [[ -z "$file" ]]; then
	file="${HOME}/Pictures/_exported/1.jpg"
fi

f=$(realpath "$file")
echo "$f"

if [[ -d "$f" ]]
	then d="$f"
elif [[ -f "$f" ]] 
	then startat="--start-at $f"
 	d=$(dirname "$f")
else 
	d="${HOME}/Pictures/_exported"
	f="${HOME}/Pictures/_exported"
fi    


# --min-dimension 256x256

# args=(--scale-down --sort "mtime" --scroll-step "50" -Z -R \
# 	--action1 ';[delete]mv -f %F /home/e/Pictures/_deleted/' \
# 	--action2 ';[twitter]cp -f %F /home/e/firejail/openbox/%N && { echo /home/e/firejail/openbox/%N | clipboard }'   \
# 	--action3 ";[export]cp -f %F /home/e/Pictures/_exported/%N" \
# 	--action4 ";[drawing]drawing %F" \
#   --geometry 720x900+720+0 \
#   --start-at "$f")


args=(--scale-down --scroll-step 200 -S mtime -R -Z --auto-zoom \
#  -p \
	--action1 ";[delete]rm %F && echo removing %F | clipboard" \
	--action2 ";[openbox]cp -f %F /home/e/firejail/openbox/%N && echo /home/e/firejail/openbox/%N | clipboard" \
	--action3 ";[assets]cp -f %F /home/e/Pictures/assets/%N" \
  --action4 ";[export]cp -f %F /home/e/Pictures/_exported/%N" \	
  --action5 ";[drawing]drawing %F" \
  --geometry 720x900+720+0 \
  --start-at "$f")


feh "${args[@]}" 
