#!/bin/bash
file="$1"
deleteddir="$HOME/Pictures/_deleted"
deletedfile="$HOME/Pictures/__delete.txt"

delete() {
  mkdir -p "$deleteddir" 2> /dev/null
  while read line; do 
    mv -f -v "$line" "$deleteddir";
  done
}


if [[ ! -f "$file" ]]; then
	file="${HOME}/Pictures/_exported/1.jpg"
fi

imgrealpath=$(realpath "$file")


if [[ -d "$file" ]]; then 
  d="$file"
elif [[ -f "$file" ]];	then 
  startat="--start-at $file"
 	d=$(dirname "$file")
else 
	d="${HOME}/Pictures/_exported"
	f="${HOME}/Pictures/_exported"
fi    


#echo file: "$file" 
#echo realpath: "$imgrealpath"
#echo dir: "$d"
#exit 0;


# --min-dimension 256x256

# args=(--scale-down --sort "mtime" --scroll-step "50" -Z -R \
# 	--action1 ';[delete]mv -f %F /home/e/Pictures/_deleted/' \
# 	--action2 ';[twitter]cp -f %F /home/e/firejail/openbox/%N && { echo /home/e/firejail/openbox/%N | clipboard }'   \
# 	--action3 ";[export]cp -f %F /home/e/Pictures/_exported/%N" \
# 	--action4 ";[drawing]drawing %F" \
#   --geometry 720x900+720+0 \
#   --start-at "$f")


args=(--scale-down --scroll-step 200 -S mtime -R -Z --auto-zoom \
#  -p \
	--action1 ";[delete]echo %F >> $deletedfile && echo removing %F | clipboard" \
	--action2 ";[openbox]cp -f %F /home/e/firejail/openbox/%N && echo /home/e/firejail/openbox/%N | clipboard" \
	--action3 ";[assets]cp -f %F /home/e/Pictures/assets/%N" \
  --action4 ";[export]cp -f %F /home/e/Pictures/_exported/%N" \	
  --action5 ";[drawing]drawing %F" \
  --geometry 720x900+720+0 \
  --start-at "$file" \
  "$d")


feh "${args[@]}" 
delete < "$deletedfile"
rm -rf "$deletedfile"
toucn "$deletefile"
echo DONE


