#!/bin/bash
pid="$1"
pid="${pid:-twitter}"
#shift
shift
cmder="$@"

#netdev="enx001e101f0000"
netdev=eth0
#netdev="enx001e101f0000"
#netfilter="/etc/firejail/nolocal.net"
netfilter="/home/e/.firejail/nolocal.net"
#netfilter6="--netfilter6=/home/e/.firejail/halo6.net"
#enx001e101f0000

#privatehome='.mozilla,.config,.tor,torrc'


#if firejail --net.print="$pid"; then 
#filter="--net=${net} --netfilter=/etc/firejail/nolocal.net --netfilter6=/etc/firejail/nolocal6.net"
#--netfilter6="$netfilter6"
#echo $netfilter
#exit;
#fi

#if ! firejail --ls="$pid" ~; then
#	firejail --name="$pid" --profile=firefox --x11=xephyr --net="${netdev}" --netfilter=1olocal --netfilter6=/etc/firejail/nolocal6.net --dns=192.168.8.1 --private="~/twitter" --noroot --caps.drop=all --disable-mnt --private-tmp --nodbus --private-dev --machine-id --noautopulse --nou2f --nodvd --notv --novideo --ipc-namespace -- openbox &


rm -rf ~/firejail/twitter.bak
mv ~/firejail/twitter ~/firejail/twitter.bak
cp -a ~/firejail/twitter.blank ~/firejail/twitter

f
args=(--name="$pid" \
	--protocol=unix,inet \
	--profile=firefox \
	--x11=xephyr \
	"--net=${netdev}" \
	"--netfilter=${netfilter}" \
	--defaultgw=192.168.8.1 \
	--ip=192.168.8.11 \
	--dns=8.8.8.8 \
	--private="~/firejail/${pid}" \
	--nonewprivs \
	--nogroups \
	--noroot \
	--caps.drop=all \
	--disable-mnt  \
	--private-tmp  \
	--nodbus \
	--private-dev \
	--machine-id  \
	--noautopulse \
	--nou2f \
	--nodvd \
#	--nosound \
	--apparmor \
	--no3d \
	--notv \
	--novideo \
	--ipc-namespace \
	qterminal)
	
#firejail "${args[@]}"

#firejail --name="$pid" --protocol=unix,inet --profile=firefox --x11=xephyr --net="${netdev}" --netfilter="$netfilter" --dns=8.8.8.8 --defaultgw=192.168.8.1 --ip=192.168.8.11 --private="~/firejail/${pid}" --noroot --nonewprivs --nogroups --noroot --caps.drop=all --disable-mnt --private-tmp --nodbus --private-dev --machine-id --noautopulse --nou2f --nodvd --no3d --notv --novideo --nosound --shell=none --ipc-namespace --deterministic-exit-code qterminal

#@	sleep 3s
#	firejail --bandwidth="$pid" set "$netdev" 24 8
#else
#	sleep 3s
#fi
#firejail --join="$pid" "$@"
#firejail --join="$pid" firefox -P "$@" &
#firejail --join="$pid" firefox "$@" &

