#!/bin/bash
display=0.0
offsetx=0
offsety=0
framerate=29
#videosize="cif"
videosize="1650x1080"
outputfilehash=$(hhash)
outputfile="$HOME/Desktop/record-${outputfilehash}.mp4"
echo ffmpeg -f x11grab -video_size "$videosize" -framerate "$framerate" -i ":${display}+${offsetx},${offsety}" "$outputfile"
ffmpeg -f x11grab -video_size "$videosize" -framerate "$framerate" -i ":${display}+${offsetx},${offsety}" "$outputfile"
