#!/bin/bash
# enable ipv4 forwarding
echo "1" > /proc/sys/net/ipv4/ip_forward

#iptables-save > /etc/iptables.save
#ip6tables-save > /etc/ip6tables.save

localnet="192.168.8.0/24"


# netfilter cleanup
iptables --flush
iptables -t nat -F
iptables -X
iptables -Z
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT
# netfilter network address translation
#iptables -t nat -A POSTROUTING -o eth0 -s $localnet -j MASQUERADE
#iptables -A INPUT -s 127.0.0.0/8 -j DROP
#iptables -A OUTPUT -d 127.0.0.0/8 -j DROP
#iptables -A INPUT -i lo -j DROP
#iptables -A OUTPUT -o lo -j DROP

#iptables -t nat -A POSTROUTING -o eth0 -s 10.10.20.0/24 -j MASQUERADE
#iptables -t nat -A POSTROUTING -o eth0 -s 10.10.30.0/24 -j MASQUERADE

#iptables -A INPUT -i lo -s 127.0.0.0/8 -j ACCEPT
#iptables -A OUTPUT -o lo -d 127.0.0.0/8 -j ACCEPT
#iptables -A INPUT -s 127.0.0.0/8 -j DROP
#iptables -A OUTPUT -d 127.0.0.0/8 -j DROP


#iptables -A INPUT -s 10.10.20.0/24 -p tcp --sport 22 -j ACCEPT
#iptables -A OUTPUT -d 10.10.20.0/24 -p tcp --dport 22 -j ACCEPT

ip6tables --flush
ip6tables -X
ip6tables -Z
ip6tables -P INPUT ACCEPT
ip6tables -P OUTPUT ACCEPT
ip6tables -P FORWARD ACCEPT
#iptables -A INPUT -i lo -j DROP
#iptables -A OUTPUT -o lo -j DROP
#ip6tables -A INPUT -j DROP
#ip6tables -A OUTPUT -j DROP
#ip6tables -A FORWARD -j DROP

rm /tmp/fw.lock

echo FIREWALL STOPPED
