#!/bin/bash
rx='kill'

if [[ -z "$1" ]]; then
	firejail --tree
elif [[ "$1" = "kill" ]]; then

	echo shutting down firejail containers
	echo ----------------------------------
	firejail --list
	firejail --list | while IFS=: read  a b c d; do firejail --shutdown="$a"; done
else
	echo shutting down firejail containers
	echo ----------------------------------
	for pid in "$@"; do
		echo firejail --shutdown="$pid"
		firejail --shutdown="$pid"
	done

fi
