#!/bin/bash
# sourced by
# -gamma_inc
# -gamma_dec

defaultgamma=10
gamma="$defaultgamma"
gammafile="$HOME/.gamma"



read_gamma() {
	read x < "$gammafile"
	gamma="$x"
}

write_gamma() {
	printf "$gamma" > "$gammafile"
}


print_gamma() {
	local gamma=$1
	a=$((gamma/10))
	b=$((gamma%10))
	printf '%s.%s' "$a" "$b"
}

gamma_inc() {
	read_gamma
	gamma=$((gamma+1))
	xgamma -gamma $(print_gamma $gamma) && write_gamma
}

gamma_dec() {
	read_gamma
	gamma=$((gamma-1))
	xgamma -gamma $(print_gamma $gamma) && write_gamma
}

gamma_reset() {
	gamma="$defaultgamma"
	xgamma -gamma $(print_gamma $gamma) && write_gamma
}





if [[ ! -f "$gammafile" ]]; then
	write_gamma
else
	read_gamma
fi

