#!/bin/bash
# sourced by
# -gamma_inc
# -gamma_dec
# -gamma_reset

#setup
defaultgamma=10
mingamma=5
maxgamma=19
gammafile="$HOME/.gamma"
#private 
print_float() {
	local gamma=$1
	a=$((gamma/10))
	b=$((gamma%10))
	printf '%s.%s' "$a" "$b"
}
store() {
    fgamma=$(print_float $gamma)
	xgamma -gamma $fgamma && printf "$gamma" > "$gammafile"
	echo "gamma $fgamma" | clipboard
}
restore() {
    if [[ ! -f $gammafile ]]; then
        gamma_reset    
    fi
	read x < "$gammafile"
	gamma="$x"
}
# interface
gamma_inc() {
	restore
	gamma=$((gamma+1))
	if [[ $gamma -gt $maxgamma ]]; then
		gamma=$maxgamma
	fi
	store
}
gamma_dec() {
	restore
	gamma=$((gamma-1))
	if [[ $gamma -lt $mingamma ]]; then
		gamma=$mingamma
	fi
	store
}
gamma_reset() {
	gamma="$defaultgamma"
	store
}
#init
restore
