#!/bin/bash
export WINEPREFIX="/home/e/.wine";
export WINEARCH="win32"
private="$HOME/firejail/halo"
dir="${WINEPREFIX}/drive_c/Program Files/Microsoft Games/Halo Custom Edition"
windir="C:\\Program Files\\Microsoft Games\\Halo Custom Edition"
netdev=eth0
netfilter="/home/e/.firejail/halo.net"
netfilter6="/home/e/.firejail/halo6.net"


rm -rf "$private"
tar -xvf "$HOME/Downloads/backup/haloce/firejail/jailhalo.tar.gz" -C "$HOME/firejail"
#cd "$dir"
#--private-tmp --noroot --caps.drop=all --disable-mnt --noautopulse 
#firejail --noprofile --name=haloce --net=$netdev --netfilter=/home/e/.firejail/nolocal.net --dns=8.8.8.8  --private-cwd="/home/e/.wine/drive_c/Program Files/Microsoft Games/Halo Custom Edition" wine start haloce.exe < /dev/null &
args=(--noprofile \
	--name=haloce \
	--protocol=unix,inet,inet6 \
	--private="$private" \
	--private-cwd="${dir}" \
	--net=$netdev \
	--netfilter="$netfilter" \
	--netfilter6="$netfilter6" \
	--dns=8.8.8.8 \
	--defaultgw=192.168.8.1 \
	--ip=192.168.8.51 \
	--caps.drop=all \
	--noroot \
	--private-dev \
	--private-tmp \
	--nonewprivs \
	--nodbus \
	--shell=none \
#	--nosound \
	--nogroups \
	--nodvd \
	--noautopulse \
	--notv \
	--novideo \
	--ipc-namespace \
	--deterministic-exit-code \
	--disable-mnt \
	--memory-deny-write-execute \
	--env=WINEDEBUG=-all \
	--env=WINEARCH="$WINEARCH" \
	--env=WINEPREFIX="$WINEPREFIX")

#( firejail "${args[@]}"	wine haloce.exe && firejail --shutdown=haloce ) &
( firejail "${args[@]}" bash && firejail --shutdown=haloce ) &
