#!/bin/bash
export WINEPREFIX="/home/e/.wine";
export WINEARCH="win32"
dir="${WINEPREFIX}/drive_c/Program Files/Microsoft Games/Halo Custom Edition"
cd "$dir"
wine start AutoHotkey.exe taxi.ahk < /dev/null &
sleep 3s
wine start haloce.exe < /dev/null &
sleep 1s
rm ~/.wine/dosdevices/com*
rm ~/.wine/dosdevices/lpt*
rm ~/.wine/dosdevices/d::
