#!/bin/bash
args=(	--net="$netdev" \
	--private-home=".irssi" \
	--dns="192.168.8.1" 
	--netfilter="/etc/firejail/nolocal.net" \
	--netfilter6="/etc/firejail/nolocal6.net" \
	-- irssi -c OFTC)

firejail "${args[@]}"
