#!/bin/bash
export WINEPREFIX="/home/e/.wine";
export WINEARCH="win32"
dir="/home/e/.wine/drive_c/Program Files/Microsoft Games/Halo Custom Edition"
windir="C:\\Program Files\\Microsoft Games\\Halo Custom Edition"

#( firejail --join=haloce wine "${windir}\\AutoHotkey.exe" "${windir}\\taxi.ahk" && firejail --join=haloce wineserver -k && firejail --shutdown=haloce ) &
#  --net=enx001e101f0000 --netfilter=/home/e/.firejail/halo.net  --dns=8.8.8.8 --defaultgw=192.168.8.1 --ip=192.168.8.22
firejail --noprofile --name=ahk "--private=/home/e/firejail/haloce" --private-dev --private-tmp --nonewprivs --nodbus "--private-cwd=${dir}" --shell=none --nogroups --nodvd --noautopulse --notv --nosound --novideo  --caps.drop=all --ipc-namespace --deterministic-exit-code --memory-deny-write-execute wine "${windir}\\AutoHotkey.exe" "${windir}\\taxi.ahk"  && firejail --shutdown=ahk

sleep 3s
rm /home/e/firejail/haloce/.wine/dosdevices/com*
rm /home/e/firejail/haloce/.wine/dosdevices/lpt*
rm /home/e/firejail/haloce/.wine/dosdevices/d::
#firejail --bandwidth=haloce set enx001e101f0000 32 32
