#!/bin/bash
#export HOME=/home/fernando
export WINEPREFIX="$HOME/.wine";
export WINEARCH="win32"
private="$HOME/firejail/halo"
dir="${WINEPREFIX}/drive_c/Program Files/Microsoft Games/Halo Custom Edition"
windir="C:\\Program Files\\Microsoft Games\\Halo Custom Edition"
netdev=br0
netfilter="$HOME/.firejail/nolocal.net"
netfilter6="$HOME/.firejail/rejectipv6.net"


rm -rf "$private"
tar -xvf "$HOME/Downloads/backup/haloce/firejail/jailhalo.tar.gz" -C "$HOME/firejail"
#cd "$dir"
#--private-tmp --noroot --caps.drop=all --disable-mnt --noautopulse 
#firejail --noprofile --name=haloce --net=$netdev --netfilter=/home/e/.firejail/nolocal.net --dns=8.8.8.8  --private-cwd="/home/e/.wine/drive_c/Program Files/Microsoft Games/Halo Custom Edition" wine start haloce.exe < /dev/null &
args=(--profile=wine \
	--name=haloce \
#  --apparmor \
	--protocol=unix,inet,inet6 \
	--private="$private" \
	--private-cwd="${dir}" \
	--net=$netdev \
	--netfilter="$netfilter" \
	--netfilter6="$netfilter6" \
	--dns=1.1.1.1 \
#	--defaultgw=192.168.8.1 \
#	--ip=192.168.8.6 \
	--caps.drop=all \
  --noinput \
	--noroot \
	--private-dev \
	--private-tmp \
#	--private-bin=sh,wine,w,wineserver,wineserver-stable,wine,haloce_1.10_cracked.exe \
	--nonewprivs \
	--nodbus \
#	--shell=none \
	--nosound \
	--nogroups \
	--nodvd \
	--noautopulse \
	--notv \
	--novideo \
	--ipc-namespace \
	--deterministic-exit-code \
	--disable-mnt \
#	--memory-deny-write-execute \
	--env=WINEDEBUG=-all \
	--env=WINEARCH="$WINEARCH" \
	--env=WINEPREFIX="$WINEPREFIX" \
    sh -c 'wine haloce_1.10_cracked.exe & wine AutoHotkey.exe taxi.ahk')
#   wine haloce.exe)

#( firejail "${args[@]}"	wine haloce.exe && firejail --shutdown=haloce ) &
#( firejail "${args[@]}" wine haloce_1.10_cracked.exe && firejail --shutdown=haloce ) &
firejail "${args[@]}"
#sleep 4s
#rm /home/e/firejail/haloce/.wine/dosdevices/com*
#rm /home/e/firejail/haloce/.wine/dosdevices/lpt*
#rm /home/e/firejail/haloce/.wine/dosdevices/d::
#firejail --join=haloce 


