#!/usr/bin/env node
var fs=require("node:fs/promises")
var cp=require("child_process")
var path=require("path")
var vm=require("vm")
var net=require("net")
var qs=require("querystring")
var stream = require("node:stream");
var { Readable, filter, compose, map } = require("node:stream");
var { compile, split, join } = require("./streammapfilter");
var getArgs=()=>process.argv.slice(2)

//run
/* 
USAGE:
  cat file | filter '(s)=>["bad","ananas"].some(ext=>String(s).includes(ext)))' 

  filters each line using a predicate function (a function returning a boolean value: true/false) 
  in this case any line that contains the keywords "bad" or "ananas"

  cat file | filter | mapf 's=>s.toUpperCase()'

  filters (by default empty lines) and then maps each line parsing a given function s=>transform(s) 
*/

//var predicate=(compileFn(getArgs().join()||"(s)=>String(s).trim().length>0"));
//var filterFn = (xs) => xs.map(s=>compileFn(s)).reduce((aggr,next)=>aggr.filter(next));

var compileAll = (args) => (data) => { 
  if(!args.length)
    args.push('s=>String(s).toUpperCase(s)');
  return args.map(s=>compile(s)).reduce((aggr,next)=>next(aggr), data); 
};

process.openStdin()
  .compose(split("\r?\n"))
  .map(compileAll(getArgs()))
  .compose(join("\n"))
	.pipe(process.stdout)
