#!/bin/bash
pid="private"
#shift
cmder="$@"

net="enx001e101f0000"
#enx001e101f0000

#privatehome='.mozilla,.config,.tor,torrc'


#if firejail --net.print="$pid"; then 
filter="--net=${net} --netfilter=/etc/firejail/nolocal.net --netfilter6=/etc/firejail/nolocal6.net"
#echo $netfilter
#exit;
#fi

if ! firejail --ls="$pid" ~; then  
    firejail --profile=firefox --name="$pid" --x11=xephyr --net=${net} --netfilter=/etc/firejail/nolocal.net --netfilter6=/etc/firejail/nolocal6.net  --dns=192.168.8.1 --noroot --caps.drop=all --disable-mnt --nonewprivs  --private-cache --private-tmp  --private="~/private" --nodbus --private-dev --machine-id  --noautopulse --nou2f --nodvd  --notv --novideo --ipc-namespace openbox &
	sleep 3
fi
firejail --join="$pid" firefox "$@" &

