#!/bin/bash
#export HOME=/home/fernando
export WINEPREFIX="$HOME/.wine";
export WINEARCH="win32"
private="$HOME/firejail/haloce"
dir="${WINEPREFIX}/drive_c/QUAKE2"
#windir="C:\\Program Files\\Microsoft Games\\Halo Custom Edition"
windir="C:\\QUAKE2"
netdev=br0
netfilter="$HOME/.firejail/halo.net"
netfilter6="$HOME/.firejail/rejectipv6.net"
#netfilter6="$HOME/.firejail/rules-ipv6.net"
archive=/media/e/3b7a9ef4-323e-45f8-a59a-658cd708459b/jailhalo.tar.gz
#archive="$HOME/Downloads/backup/haloce/firejail/jailhalo.tar.gz"
if [[ -z $1 ]]; then 
#  cmd=(sh -c 'wine haloce_1.10_cracked.exe -console & wine AutoHotkey.exe taxi.ahk')
#  cmd=(wine haloce_1.10_cracked.exe -console)
  cmd=(wine quake2)
else
  cmd="$@"
fi


#rm -rf "$private"
#tar -xvf "$archive" -C "$HOME/firejail"
#cd "$dir"
#--private-tmp --noroot --caps.drop=all --disable-mnt --noautopulse 
#firejail --noprofile --name=haloce --net=$netdev --netfilter=/home/e/.firejail/nolocal.net --dns=8.8.8.8  --private-cwd="/home/e/.wine/drive_c/Program Files/Microsoft Games/Halo Custom Edition" wine start haloce.exe < /dev/null &
args=(--name=haloce \
  --profile=wine \
#	--noprofile \
#  --apparmor \
	--protocol=unix,inet,inet6 \
	--private="$private" \
	--private-cwd="${dir}" \
	--net=$netdev \
	--netfilter="$netfilter" \
	--netfilter6="$netfilter6" \
	--dns=1.1.1.1 \
#  --dns=8.8.8.8 \
#	--defaultgw=192.168.8.1 \
#	--ip=192.168.8.6 \
	--caps.drop=all \
  --noinput \
	--noroot \
	--private-tmp \
#	--private-bin=sh,wine,w,wineserver,wineserver-stable,wine,haloce_1.10_cracked.exe \
	--nonewprivs \
	--nodbus \
#	--shell=none \
	--nosound \
	--nogroups \
	--noautopulse \
	--notv \
	--novideo \
	--ipc-namespace \
	--deterministic-exit-code \
#	--memory-deny-write-execute \
	--env=WINEDEBUG=-all \
	--env=WINEARCH="$WINEARCH" \
	--env=WINEPREFIX="$WINEPREFIX" \
  --read-only="/media" \
  --read-only="/media/e" \
  --read-only="/media/e/SKYRIM_DE" \
#    sh -c 'wine haloce_1.10_cracked.exe & wine AutoHotkey.exe taxi.ahk')
#   wine msiexec /uninstall msxmlmenu.msi)
    "${cmd[@]}")

#   wine haloce.exe)

#( firejail "${args[@]}"	wine haloce.exe && firejail --shutdown=haloce ) &
#( firejail "${args[@]}" wine haloce_1.10_cracked.exe && firejail --shutdown=haloce ) &
firejail "${args[@]}"
#sleep 4s
#rm /home/e/firejail/haloce/.wine/dosdevices/com*
#rm /home/e/firejail/haloce/.wine/dosdevices/lpt*
#rm /home/e/firejail/haloce/.wine/dosdevices/d::
#firejail --join=haloce 


