#!/bin/bash
export WINEPREFIX="/home/e/.wine";
export WINEARCH="win32"
dir="/home/e/.wine/drive_c/Quake"
windir="C:\\Quake"
netdev=eth0
#cd "$dir"wine "C:\\Quake\\qlaunch.exe" quakeudp.dll quake.exe -mpath $* && firejail --shutdown=quake
#--private-tmp --noroot --caps.drop=all --disable-mnt --noautopulse 
#firejail --noprofile --name=haloce --net=$netdev --netfilter=/home/e/.firejail/nolocal.net --dns=8.8.8.8  --private-cwd="/home/e/.wine/drive_c/Program Files/Microsoft Games/Halo Custom Edition" wine start haloce.exe < /dev/null &
firejail --name=quake "--private=/home/e/firejail/quake" --net=$netdev --netfilter=/home/e/.firejail/halo.net --netfilter6=/home/e/.firejail/halo6.net --dns=8.8.8.8 --defaultgw=192.168.8.1 --ip=192.168.8.21 --caps.drop=all --noroot --private-dev --private-tmp --nonewprivs --nodbus --private-cwd="${dir}" --nogroups --nodvd --noautopulse --notv --novideo --ipc-namespace --deterministic-exit-code --disable-mnt --env=WINEDEBUG=-all --env=WINEARCH=win64 --env=WINEPREFIX=/home/e/.wine wine quakespasm
#sleep 3s
#rm /home/e/firejail/haloce/.wine/dosdevices/com*
#rm /home/e/firejail/haloce/.wine/dosdevices/lpt*
#rm /home/e/firejail/haloce/.wine/dosdevices/d::
#firejail --join=haloce wine "${windir}\\AutoHotkey.exe" "${windir}\\taxi.ahk"


