#!/bin/bash
args=($*)
PIDFILE="/tmp/rec.pid"
echo "$$" > "$PIDFILE"
if [[ "${#args}" =~ 0 ]]; then
  clipbrd=$(xsel -ob)
  args+=("${clipbrd:-record}")
fi
filename=$(zenity --entry --text="title" --entry-text="${args[@]}")


trap 'rm -rf "$PIDFILE"; mp3 "$filename"; trap - INT; kill -s INT "$$"' INT

arecord -vv --format=cd /tmp/record.wav
