#!/bin/bash
#sudo=sudo
sleep 4s
rmmod mei_hdcp
rmmod mei_me
rmmod mei
rmmod option
rmmod btrfs
rmmod raid6_pq
rmmod xor
rmmod option
rmmod usb_wwan
rmmod usbserial
rmmod uas
rmmod x86_pkg_temp_thermal
rmmod br_netfilter
#sudo ifbr0
#netdev=enx001e101f0000
export netdev=eth0
#sudo ip link set $netdev down
sleep 1s
#ip link set dev "$netdev" up
#ip addr add 192.168.8.2/24 brd + dev "$netdev"
#ip route add default via 192.168.8.1 dev "$netdev"
#echo nameserver 192.168.8.1 > /etc/resolv.conf
#sleep 1s
#sudo dhclient $netdev
rm -rf /home/e/.cache/mesa_shader_cache
rm -rf /home/e/.cache/thumbnails/*
rm -rf /home/e/.cache/fontconfig
rm -rf /run/user/1000/at*
#sudo rm 
#sudo rm -rf /var/lib/dhcp/*
#/etc/init.d/networking restart
sleep 2s
/usr/local/sbin/setup-bridge
sleep 1s
#/usr/local/sbin/vmalpine
#ipaddr=$(ip addr)
#sudo -u e -g e notify "$ipaddr"
#sudo ifbr0
#sudo ip addr
#sudo ip link set eth0 up
