#!/bin/bash
custom="$1"
default='s=>String(s)';
custom="${custom:-$default}";
#custom="'$custom'";
#exit 0;
transliterate(){ mapf 's=>{ var u=require("unidecode"); var p=String(s).split("/"); var f=p.splice(-1)[0].split(".");  var parent=p.length>1?p.join("/").replaceAll(" ","\ "):""; var ext=`.${f.length>1?f.splice(-1)[0]:""}`.toLowerCase(); var basename=u(f.join(".")).replaceAll(/[^a-zA-Z0-9\.]+/g, "-").replaceAll(/^[-]*|[-]*$/g,"").replaceAll(/[-]{2,}/g,"-").toLowerCase(); var fullPath=`${parent}/${basename}`; if(ext) fullPath+=`${ext}`; return `${fullPath} ${String(s).replaceAll(" ","\ ")}`; }'; };
#transliterateCustom(){ mapf "'"$1"'"; };
filter-file \
  | transliterate \
  | while read newname file; do 
  	#echo "[$newname] [$file]"; 
      if [[ -f $newname ]]; then
        #printf '[%s][%s]\n' "$file" "$newname";
        tmpfilesum=($(sha1sum -b "$file"))
        tmpnewnamesum=($(sha1sum -b "$newname"))
        filesum="${tmpfilesum[0]}"
        newnamesum="${tmpnewnamesum[0]}"
        if [[ ! $newnamesum = $filesum ]]; then
          #printf '[%s][%s]\n' "$filesum" "$newnamesum";
          hsh=$(hhash 3);
          pathbegin="${line%.*}"; 
          ext=".${line#*.}"; 
          newname="${pathbegin}${hsh}${ext}";
          mv -f "$file" "$newname" > /dev/null 2>&1 && printf %s\\n "$newname"
        else 
          printf %s\\n "$newname"
        fi
      elif [[ ! $newname = $file ]]; then
        mv -f "$file" "$newname" > /dev/null 2>&1 && printf %s\\n "$newname"
      else 
          printf %s\\n "$newname"
      fi
    done \
  | clipboard
