#!/bin/bash
# bridge setup   
#ip link del br0
sleep 1s
brctl addbr br0   
ifconfig br0 10.10.20.1/24 up  
sleep 1s

#/usr/local/sbin/qemu-ifup


#ip link add dev br0 type bridge
#ip link set dev br0 up
#ip addr add 10.10.20.0/24 brd + dev br0

# enable ipv4 forwarding
echo "1" > /proc/sys/net/ipv4/ip_forward

# netfilter cleanup
iptables --flush
iptables -t nat -F
iptables -X
iptables -Z
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD ACCEPT
# netfilter network address translation
iptables -t nat -A POSTROUTING -o eth0 -s 10.10.20.0/24 -j MASQUERADE
#iptables -t nat -A POSTROUTING -o eth0 -s 10.10.30.0/24 -j MASQUERADE

#iptables -A INPUT -i lo -s 127.0.0.0/8 -j ACCEPT
#iptables -A OUTPUT -o lo -d 127.0.0.0/8 -j ACCEPT
#iptables -A INPUT -s 127.0.0.0/8 -j DROP
#iptables -A OUTPUT -d 127.0.0.0/8 -j DROP


iptables -A INPUT -s 10.10.20.0/24 -p tcp --sport 22 -j ACCEPT
iptables -A OUTPUT -d 10.10.20.0/24 -p tcp --dport 22 -j ACCEPT

ip6tables --flush
ip6tables -t nat -F
ip6tables -X
ip6tables -Z
ip6tables -P INPUT DROP
ip6tables -P OUTPUT DROP
ip6tables -P FORWARD DROP
ip6tables -A INPUT -j DROP
ip6tables -A OUTPUT -j DROP
ip6tables -A FORWARD -j DROP




#host port 80 forwarded to sandbox port 80   
#iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to 10.10.20.10:80
