#!/usr/bin/env node
var fs=require('fs');
var path=require('path');
var util=require('util')
var {execSync,exec,spawn}=require('child_process');
var es=require('event-stream');

//spawn(process.argv[3], process.argv.slice(3)).stdout
process.openStdin()
	.pipe(es.split(/\n/))
	.pipe(es.map((data,cb)=>{
		var xs=data.replace(/(\s)+/g,"\t").split(/\t/);
		if(data.length) {
			cb(null,xs)
		} else {
			cb(null)
		}
	}))
	.pipe(es.stringify())
	.pipe(process.stdout)

