#!/bin/bash
firejail --net=eth0 --netfilter=/home/e/.firejail/nolocal_.net --netfilter6=/home/e/.firejail/rejectipv6.net --protocols=inet,inet6 --private=/home/e/tor-browser_en-US --private-cwd ./start-tor-browser.desktop
