#!/bin/bash

pid="${PID:-torbox}"
dns="${DNS:-8.8.8.8}"
hostname="${HOSTNAME:-torbox}"
netdev="${NETDEV:-$netdev}"
protocol="${PROTOCOL:-inet,inet6}"
private="$PRIVATE"

prepareHome(){
	mkdir -p "$HOME/firejail" 2> /dev/null
	home="$HOME/firejail/$pid"
	rm -rf "$home"
	mkdir -p "$home" 2> /dev/null
	mkdir -p "$home/.local"
	cp -a "$HOME/git/ea-bash-script" "$home/.local"
	mv "$home/.local/ea-bash-script" "$home/.local/bin"
	cp -a "$HOME/.irssi" "$home"
	cp -a "$HOME/.tor" "$home"
	cp -a "$HOME/torrc" "$home"
	cp -a "$HOME/.bashrc" "$home"
	cp -a "$HOME/.profile" "$home"

}

prepareHome 2> /dev/null

args=(--name="$pid" \
	--noprofile \
	--protocol="$protocol" \
	--private="$home" \
	--private-cwd \
	--net="$netdev" \
#	--netfilter="$HOME/.firejail/tor.net" \
	--netfilter="$HOME/.firejail/nolocal_.net" \
	"--netfilter6=$HOME/.firejail/rejectipv6.net" \
	--dns="$dns" \
#	--tmpfs=.tor
#	--hostname="$hostname" \
	--hosts-file="$HOME/.firejail/torbox.hosts" \
	--nogroups \
	--nonewprivs \
	--disable-mnt \
	--private-tmp \
	--seccomp \
	--caps.drop=all \
	--private-dev \
	--private-tmp \
	--noroot \
	--nogroups \
#	--ipc-namespace \
	--nosound \
	--noautopulse \
	--nodbus \
	--restrict-namespaces \
	--deterministic-exit-code \
	--env=PATH=$PATH \
	--env=JAIL=torbox \
	--env=PS1='$ ')
echo firejail "${args[@]}" "$@"
echo '==========================='
firejail "${args[@]}" "$@"
