#!/bin/bash
echo "var videolist=" > /home/e/git/http/video/videolist.js;  p /media/e/3b7a9ef4-323e-45f8-a59a-658cd708459b/mp4/* /media/e/bbR7qvRSTN4BmaJ1/porn/**/* "$@" |  p2json  >> /home/e/git/http/video/videolist.js
cat /home/e/git/http/video/videolist.js