#!/bin/sh
# This script created by AQEMU
/usr/bin/qemu-system-x86_64  -smp 2 -soundhw ac97 -machine accel=kvm -m 3014 -snapshot -hda "/media/iso/linux.derived-2.qcow2" -virtfs local,id=shared_folder_dev_0,path=/shared,security_model=none,mount_tag=shared0 -boot once=c,menu=on -net nic -net user -rtc base=utc,driftfix=slew -name "Linux" $*
