#!/bin/sh
# This script created by AQEMU
/usr/bin/qemu-system-x86_64  -loadvm aqemu_save -smp 2 -soundhw sb16 -machine accel=kvm -m 2690 -snapshot -hda "/media/iso/linux.derived-2.qcow2" -virtfs local,id=shared_folder_dev_0,path=/tmp/shared0,security_model=none,mount_tag=shared0 -boot once=c,menu=on -net nic -net tap,ifname=tap0,script=no -rtc base=localtime,driftfix=slew -name "Linux2" $*
