#!/bin/sh
# This script created by AQEMU
/usr/bin/qemu-system-x86_64  -soundhw ac97 -machine accel=kvm -m 3183 -snapshot -hda "/home/eagle/.aqemu/linux.derived.qcow2" -virtfs local,id=shared_folder_dev_0,path=/shared,security_model=none,mount_tag=shared0 -boot once=c,menu=on -net nic,macaddr=00:e1:7f:cd:7c:c0 -net tap,ifname=tap0,script="/home/eagle/.bin/qemu-ifup" -rtc base=utc,driftfix=slew -name "Linux" $*
