#!/usr/bin/env node
var {walk,walkAsync}=require("ea-1ibs");

var targetDir=process.argv.slice(2).join(" ");

//[...walk(target)].forEach(entry=>console.log(entry));

(async()=>{ 
	for await (var entry of walkAsync(targetDir||process.cwd())) {
		var jsonString=JSON.stringify(entry);
		process.stdout.write(jsonString.replaceAll(/\n/g,"")+"\n");
//		console.log(jsonString);
//		try { var json=JSON.parse(jsonString); } catch(e) { console.log(e);	}
		
	} 
})()

