#!/bin/bash
# --compression=gzip
wget -c -nc -x -E --connect-timeout 3 --dns-timeout 3 --max-redirect 3 -t 1 --show-progress --compression=auto --secure-protocol=TLSv1_2 --no-check-certificate --auth-no-challenge    $*
