#!/bin/bash
ifconfig $dev down
sleep 1s
ifconfig $dev 192.168.42.11 netmask 255.255.255.0 broadcast 192.168.42.255
sleep 1s
echo nameserver 8.8.8.8 > /etc/resolv.conf
echo nameserver 127.0.0.1 >> /etc/resolv.conf
sleep 1s
ip addr show
(ip route add default via 192.168.42.129 dev $dev && ip route list)
