#!/bin/bash

# source: https://blog.abysm.org/2020/03/realtek-802-11ac-usb-wi-fi-linux-driver-installation/

s='sudo';
#wget https://http.kali.org/kali/pool/contrib/r/realtek-rtl88xxau-dkms/realtek-rtl88xxau-dkms_5.6.4.2~git20210327.c0ce817-0kali2_all.deb
#wget https://http.kali.org/kali/pool/contrib/r/realtek-rtl8814au-dkms/realtek-rtl8814au-dkms_5.8.5.1~git20210331.bdf80b5-0kali1_all.deb

#$s apt update

apt install ./realtek-rtl88xxau-dkms_5.6.4.2~git20210327.c0ce817-0kali2_all.deb ./realtek-rtl8814au-dkms_5.8.5.1~git20210331.bdf80b5-0kali1_all.deb
