#!/bin/bash

declare -A search=( \
	[g]='https://google.com/search?q=' \
	[d]='https://duckduckgo.com/?q=' \
)

searchengine=$1

url=${search[$searchengine]}
if [[ ! -z_$url ]]; then
#	url=${search[g]};
	echo "[ $1 ] ${url}"
	shift;
else
 echo 'starting lynx $*'
fi


query="$url$*"

echo lynx "$query"
# || lynx "$query"'

#TORSOCKS_USERNAME=eagle1 TORSOCKS_PASSWORD=foxforcefive torsocks
lynx "$query"
#lynx "$query"
