#!/bin/bash
#firejail --net=none --x11=xephyr--name=codebox --read-write=/home/eagle --read-write=/tmp/shared0 --private-dev  --noroot /tmp/shared0/bin/codebox
firejail --join-or-start=vlcbox --seccomp --noprofile --net=none --x11=xephyr --xephyr-screen=1440x870 --private-cache --disable-mnt --noroot openbox-session &
#source /tmp/shared0/bin/codebox
sleep 5
firejail --join=vlcbox /usr/bin/vlc "$*"
